### ISSUE TITLE
Can´t use Spotify as Source for Artist/Song and Artist Radio

### ISSUE THREAD

**Issue by evildrummer** [4meuwil/alexa2.0#1]
Hi,

i primarily use Spotify and i tried to use "music" as the "media_content_type".
At the device stats in Hass.io there is "music" the media_content_type in all of my echo dots when i play music from Spotify.

EDIT:

Nevermind, it´s working with "SPOTIFY" as media_content_type and i deleted the + "radio"

Sorry :)

**Comment by 4meuwil** [comment]
"media_content_type": "SPOTIFY" is the correct call for Spotify, but requires a premium account set up in the alexa app.
